<?php

namespace App\Imports;

use App\Models\Teacher;
use App\Models\Subject;
use App\Models\Schedule;
use App\Models\LoadPeriod;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;

use Maatwebsite\Excel\Concerns\ToModel;


class LoadPeriodsImport implements ToModel
{

    protected $period;
    protected $load_period;


    public function __construct()
    {
        $month        = date('m');
        $semester     = (int)floor(($month-1)/6)+1;
        $this->period = date('Y') . '-' . $semester;

        $this->load_period = LoadPeriod::create([
            'user_id'   => Auth::id(),
            'file_name' => request()->file('file')->getClientOriginalName(),
            'period'    => $this->period
        ]);

    }



    public function model(array $row)
    {
            $total_hours= '100';

            $data = [
                    [
                'subject_id'          => '215',
                'program_id'          => '4',
                'teacher'             => '22',
                'area_id'             => '21',
                'campus'              => '10',
                'group'               => '1',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '5',
                'start_hour'          => '6',
                'start_minute'        => '0',
                'end_hour'            => '8',
                'end_minute'          => '0',
                'classroom'           => 'P17-102',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '40',
                'scheduled_capacity'  => '10',
                'enrolled'            => '9',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '215',
                'program_id'          => '4',
                'teacher'             => '46',
                'area_id'             => '21',
                'campus'              => '10',
                'group'               => '2',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '4',
                'start_hour'          => '12',
                'start_minute'        => '0',
                'end_hour'            => '14',
                'end_minute'          => '0',
                'classroom'           => 'P17-109',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '40',
                'scheduled_capacity'  => '10',
                'enrolled'            => '9',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '215',
                'program_id'          => '4',
                'teacher'             => '46',
                'area_id'             => '21',
                'campus'              => '10',
                'group'               => '2',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '4',
                'start_hour'          => '14',
                'start_minute'        => '0',
                'end_hour'            => '16',
                'end_minute'          => '0',
                'classroom'           => 'P17-202',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '40',
                'scheduled_capacity'  => '10',
                'enrolled'            => '9',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '215',
                'program_id'          => '4',
                'teacher'             => '57',
                'area_id'             => '21',
                'campus'              => '10',
                'group'               => '3',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '1',
                'start_hour'          => '6',
                'start_minute'        => '0',
                'end_hour'            => '8',
                'end_minute'          => '0',
                'classroom'           => 'P13-101',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '40',
                'scheduled_capacity'  => '10',
                'enrolled'            => '9',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '215',
                'program_id'          => '4',
                'teacher'             => '71',
                'area_id'             => '21',
                'campus'              => '10',
                'group'               => '4',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '2',
                'start_hour'          => '6',
                'start_minute'        => '0',
                'end_hour'            => '8',
                'end_minute'          => '0',
                'classroom'           => 'P40-301',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '42',
                'scheduled_capacity'  => '10',
                'enrolled'            => '9',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '215',
                'program_id'          => '4',
                'teacher'             => '71',
                'area_id'             => '21',
                'campus'              => '10',
                'group'               => '4',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '4',
                'start_hour'          => '6',
                'start_minute'        => '0',
                'end_hour'            => '8',
                'end_minute'          => '0',
                'classroom'           => 'P40-301',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '42',
                'scheduled_capacity'  => '10',
                'enrolled'            => '9',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '215',
                'program_id'          => '4',
                'teacher'             => '57',
                'area_id'             => '21',
                'campus'              => '10',
                'group'               => '5',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '6',
                'start_hour'          => '6',
                'start_minute'        => '0',
                'end_hour'            => '8',
                'end_minute'          => '0',
                'classroom'           => 'P13-116',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '40',
                'scheduled_capacity'  => '10',
                'enrolled'            => '9',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '215',
                'program_id'          => '4',
                'teacher'             => '57',
                'area_id'             => '21',
                'campus'              => '10',
                'group'               => '5',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '6',
                'start_hour'          => '8',
                'start_minute'        => '0',
                'end_hour'            => '10',
                'end_minute'          => '0',
                'classroom'           => 'P17-102',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '40',
                'scheduled_capacity'  => '10',
                'enrolled'            => '9',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '361',
                'program_id'          => '7',
                'teacher'             => '75',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '1',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '3',
                'start_hour'          => '14',
                'start_minute'        => '0',
                'end_hour'            => '16',
                'end_minute'          => '0',
                'classroom'           => 'P17-307',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '40',
                'scheduled_capacity'  => '8',
                'enrolled'            => '4',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '361',
                'program_id'          => '7',
                'teacher'             => '75',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '1',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '5',
                'start_hour'          => '14',
                'start_minute'        => '0',
                'end_hour'            => '16',
                'end_minute'          => '0',
                'classroom'           => 'P17-307',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '40',
                'scheduled_capacity'  => '8',
                'enrolled'            => '4',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '361',
                'program_id'          => '7',
                'teacher'             => '75',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '1',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '5',
                'start_hour'          => '14',
                'start_minute'        => '0',
                'end_hour'            => '16',
                'end_minute'          => '0',
                'classroom'           => 'P17-307',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '40',
                'scheduled_capacity'  => '8',
                'enrolled'            => '4',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '361',
                'program_id'          => '7',
                'teacher'             => '75',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '11',
                'detail'              => 'Grupo de CLASE PRACTICA.',
                'day'                 => '1',
                'start_hour'          => '8',
                'start_minute'        => '0',
                'end_hour'            => '10',
                'end_minute'          => '0',
                'classroom'           => 'P13-208',
                'activity'            => 'PRACTICA',
                'classroom_capacity'  => '30',
                'scheduled_capacity'  => '8',
                'enrolled'            => '6',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '361',
                'program_id'          => '7',
                'teacher'             => '75',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '12',
                'detail'              => 'Grupo de CLASE PRACTICA.',
                'day'                 => '1',
                'start_hour'          => '14',
                'start_minute'        => '0',
                'end_hour'            => '16',
                'end_minute'          => '0',
                'classroom'           => 'P13-208',
                'activity'            => 'PRACTICA',
                'classroom_capacity'  => '30',
                'scheduled_capacity'  => '8',
                'enrolled'            => '8',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '361',
                'program_id'          => '7',
                'teacher'             => '77',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '13',
                'detail'              => 'Grupo de CLASE PRACTICA.',
                'day'                 => '2',
                'start_hour'          => '6',
                'start_minute'        => '0',
                'end_hour'            => '8',
                'end_minute'          => '0',
                'classroom'           => 'P13-303',
                'activity'            => 'PRACTICA',
                'classroom_capacity'  => '30',
                'scheduled_capacity'  => '8',
                'enrolled'            => '6',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '361',
                'program_id'          => '7',
                'teacher'             => '75',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '2',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '3',
                'start_hour'          => '10',
                'start_minute'        => '0',
                'end_hour'            => '12',
                'end_minute'          => '0',
                'classroom'           => 'P17-307',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '40',
                'scheduled_capacity'  => '8',
                'enrolled'            => '8',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '361',
                'program_id'          => '7',
                'teacher'             => '75',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '2',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '5',
                'start_hour'          => '10',
                'start_minute'        => '0',
                'end_hour'            => '12',
                'end_minute'          => '0',
                'classroom'           => 'P17-307',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '40',
                'scheduled_capacity'  => '8',
                'enrolled'            => '8',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '361',
                'program_id'          => '7',
                'teacher'             => '77',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '3',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '1',
                'start_hour'          => '6',
                'start_minute'        => '0',
                'end_hour'            => '8',
                'end_minute'          => '0',
                'classroom'           => 'P17-307',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '40',
                'scheduled_capacity'  => '8',
                'enrolled'            => '8',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '361',
                'program_id'          => '7',
                'teacher'             => '77',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '3',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '5',
                'start_hour'          => '6',
                'start_minute'        => '0',
                'end_hour'            => '8',
                'end_minute'          => '0',
                'classroom'           => 'P17-307',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '40',
                'scheduled_capacity'  => '8',
                'enrolled'            => '8',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '375',
                'program_id'          => '7',
                'teacher'             => '38',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '1',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '5',
                'start_hour'          => '6',
                'start_minute'        => '0',
                'end_hour'            => '8',
                'end_minute'          => '0',
                'classroom'           => 'P13-209',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '30',
                'scheduled_capacity'  => '20',
                'enrolled'            => '14',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '375',
                'program_id'          => '7',
                'teacher'             => '73',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '10',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '4',
                'start_hour'          => '6',
                'start_minute'        => '0',
                'end_hour'            => '8',
                'end_minute'          => '0',
                'classroom'           => 'P13-207',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '31',
                'scheduled_capacity'  => '20',
                'enrolled'            => '14',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '375',
                'program_id'          => '7',
                'teacher'             => '49',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '11',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '4',
                'start_hour'          => '8',
                'start_minute'        => '0',
                'end_hour'            => '10',
                'end_minute'          => '0',
                'classroom'           => 'P13-207',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '31',
                'scheduled_capacity'  => '20',
                'enrolled'            => '20',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '375',
                'program_id'          => '7',
                'teacher'             => '49',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '12',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '4',
                'start_hour'          => '10',
                'start_minute'        => '0',
                'end_hour'            => '12',
                'end_minute'          => '0',
                'classroom'           => 'P13-303',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '30',
                'scheduled_capacity'  => '20',
                'enrolled'            => '20',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '375',
                'program_id'          => '7',
                'teacher'             => '32',
                'area_id'             => '24',
                'campus'              => '40',
                'group'               => '120',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '2',
                'start_hour'          => '20',
                'start_minute'        => '0',
                'end_hour'            => '22',
                'end_minute'          => '0',
                'classroom'           => 'A04-102',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '40',
                'scheduled_capacity'  => '20',
                'enrolled'            => '16',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '375',
                'program_id'          => '7',
                'teacher'             => '44',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '13',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '4',
                'start_hour'          => '20',
                'start_minute'        => '0',
                'end_hour'            => '22',
                'end_minute'          => '0',
                'classroom'           => 'P13-209',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '30',
                'scheduled_capacity'  => '20',
                'enrolled'            => '9',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '375',
                'program_id'          => '7',
                'teacher'             => '49',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '14',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '4',
                'start_hour'          => '12',
                'start_minute'        => '0',
                'end_hour'            => '14',
                'end_minute'          => '0',
                'classroom'           => 'P13-304',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '30',
                'scheduled_capacity'  => '20',
                'enrolled'            => '17',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '375',
                'program_id'          => '7',
                'teacher'             => '38',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '15',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '5',
                'start_hour'          => '8',
                'start_minute'        => '0',
                'end_hour'            => '10',
                'end_minute'          => '0',
                'classroom'           => 'P13-304',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '30',
                'scheduled_capacity'  => '20',
                'enrolled'            => '20',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '375',
                'program_id'          => '7',
                'teacher'             => '23',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '16',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '1',
                'start_hour'          => '18',
                'start_minute'        => '0',
                'end_hour'            => '20',
                'end_minute'          => '0',
                'classroom'           => 'P13-208',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '30',
                'scheduled_capacity'  => '20',
                'enrolled'            => '19',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '375',
                'program_id'          => '7',
                'teacher'             => '25',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '2',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '4',
                'start_hour'          => '18',
                'start_minute'        => '0',
                'end_hour'            => '20',
                'end_minute'          => '0',
                'classroom'           => 'P13-209',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '30',
                'scheduled_capacity'  => '20',
                'enrolled'            => '13',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '375',
                'program_id'          => '7',
                'teacher'             => '25',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '3',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '3',
                'start_hour'          => '8',
                'start_minute'        => '0',
                'end_hour'            => '10',
                'end_minute'          => '0',
                'classroom'           => 'P13-209',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '30',
                'scheduled_capacity'  => '20',
                'enrolled'            => '18',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            [
                'subject_id'          => '375',
                'program_id'          => '7',
                'teacher'             => '48',
                'area_id'             => '24',
                'campus'              => '10',
                'group'               => '30',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '1',
                'start_hour'          => '18',
                'start_minute'        => '0',
                'end_hour'            => '20',
                'end_minute'          => '0',
                'classroom'           => 'P13-314',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '30',
                'scheduled_capacity'  => '20',
                'enrolled'            => '1',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ],
            ];

            Schedule::insert($data);

            return (new Schedule([
                'subject_id'          => '215',
                'program_id'          => '4',
                'teacher'             => '22',
                'area_id'             => '21',
                'campus'              => '10',
                'group'               => '1',
                'detail'              => 'Grupo de CLASE TEORICA.',
                'day'                 => '3',
                'start_hour'          => '6',
                'start_minute'        => '0',
                'end_hour'            => '8',
                'end_minute'          => '0',
                'classroom'           => 'P17-109',
                'activity'            => 'TEORICA',
                'classroom_capacity'  => '40',
                'scheduled_capacity'  => '10',
                'enrolled'            => '9',
                'plan'                => '1',
                'total_hours'         => $total_hours,

                'evaluation_hours'    => $total_hours/2,
                'observations'        => 'NONE',
                'offer'               => 's',
                'updated_by'          => '1',
                'status'              => 'Pendiente',
                'load_id'             => $this->load_period->id,
            ]
            )
            );

    }
}
